### PR TITLE
Command to Save things into tng file

### PR DESCRIPTION
**Pull request by SimLV**

### CODE REVIEW

**Comment by Loobinex** [comment]
I don't know how to test this.
I tried putting !save.tng in the console, but get errors like these in the log:
`Error: cmd_save_tng: Unknown thing oclass: 3`

Also, this again has the error of not allowing me to press E in the console. I cherry-picked the fix locally to get it to work.

**Comment by SimLV** [comment]
> Also, this again has the error of not allowing me to press E in the console. I cherry-picked the fix locally to get it to work.
It looks like it disappeared from master branch

**Comment by SimLV** [comment]
> I don't know how to test this.
> I tried putting !save.tng in the console, but get errors like these in the log:
Fixed. 
I just want to place custom traps on a map from game because I am unable to build map editor.

**Comment by Loobinex** [comment]
I tried, still don't know what this does. I ran the command, now there's no error message in the log, but I don't see anything happen. How do I use this command and what does it do? Looking at the code did not help me.

**Comment by Loobinex** [comment]
@SimLV Is this still relevant or shall I close it?

**Comment by SimLV** [comment]
Outdated. This feature is to heavy to support.

**Pull request closed without merging**
