### PR TITLE
Memory

### PR DESCRIPTION
**Pull request by AdamPlenty**

### CODE REVIEW

**Comment by Loobinex** [comment]
What does this do? And how to test it?

**Comment by AdamPlenty** [comment]
> 
> 
> What does this do? And how to test it?

I'm not sure what it does, but you can test it by looking at the log file (in the statement 'PhysicalMemory'). Theoretically this should double the amount of memory available to KeeperFX.

**Comment by Loobinex** [comment]
I always lean towards 'if it ain't broken, don't fix it', especially if we don't know exactly what we're doing. I don't even know why it was commented out in the first place, but I see it was never enabled. It went from non-existent to commented out straight away.

I'll check it out, but I find it very dangerous, because will we ever find out if it starts to crash only after we use too much memory, especially if you usually don't use as much?

**Comment by Loobinex** [comment]
I looked into it, and I think we should not make this change. Tell me what you think.

I believe that all that these lines of code do, is set the variable 'mem_size'. And that variable does not determine how much memory the game can use, but based on this variable the memory intensive features are disabled. The current highest value (32 Mb), already has all features enabled, so giving it an even bigger value does absolutely nothing.

With bigger values  enabled, we could in the future when we add even more memory intensive features, like really high def graphics or something, disable those features when you don't have enough memory for them, but enough to use all the current features. But it makes more sense to set this up only when the need arrives.

**Pull request closed without merging**
