### PR TITLE
Map screen duplicates appear to be fixed

### PR DESCRIPTION
**Pull request by spartahawk**
I've only tested on level 17, but after they had fully dug-out the level, still none of the pesky duplicates. Please confirm.

### CODE REVIEW

**Comment by Loobinex** [comment]
I can confirm the bug is fixed. Great.
I'll do some regression testing later today before merging.

**Comment by spartahawk** [comment]
You mentioned there were problems caused by unrelated changes mefisto made
leading up to the map duplicates fix. Hopefully I've managed to leave those
out. Let me know.

**Comment by Loobinex** [comment]
Everything seemed fine, so I merged your pull request.

**Comment by spartahawk** [comment]
Awesome. I'll start looking at the recent rooms bug. I'll test the official
keeperfx to make sure it isn't just our version, unless you already did.

**Pull request merged**
