### PR TITLE
Can now be compiled with MSYS2 mingw32

### PR DESCRIPTION
**Pull request by Real-Gecko**
However it'll require `libwinpthread-1.dll` from MSYS2 in game folder.

### CODE REVIEW

**Comment by Loobinex** [comment]
@Real-Gecko Yes, this should be able to be build without this change, and more importantly, without requiring an additional dll. What's the error you used to get before you made the change from this pull?

I use WSL to build by the way:
```
Open Powershell as Administrator and type: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux". Restart.
Go here: https://www.microsoft.com/store/apps/9N9TNGVNDL3Q to install Ubuntu 18.04 from windows store.

Type: "sudo apt update && sudo apt upgrade" and confirm

sudo apt install make
sudo apt install unzip
sudo apt install gcc
sudo apt install g++
sudo apt-get install gcc-mingw-w64-i686
sudo apt-get install g++-mingw-w64-i686
```

**Comment by AdamPlenty** [comment]
I can build in MSYS2, but the exe file does require the additional DLL file.

**Comment by Real-Gecko** [comment]
> I've been compiling this with MSYS2 minigw32 for ages...

Which version of MSYS2 do you use? I've installed version 20200720 and used pacman to install mingw32. It turns out that MSYS2 tar does not support `--no-anchored` flag, which is odd, that's why I changes `libexterns.mk`.
During linking stage I had an error `multiple definition of atktyp first defined here` in various files that included `creature_states_combt.h` that's why I removed it from `creature_states_combt.h`, this variable can be completely removed anyway. And about `libwinpthread-1.dll` I don't know why it's became required, maybe some changes in newer versions of mingw32.

**Comment by Real-Gecko** [comment]
OK, I've figured it out. By default MSYS2 installs `bsdtar` as a part of `base` group, and it does not support  `--no-anchored` flag. But I can install `tar` package that'll override `bsdtar` and does support this flag, so changes to `libexterns.mk` are not needed. However it leaves `multiple definition of atktyp first defined here` error unresolved.

**Comment by Loobinex** [comment]
ok, update this pull to remove the changes to the makefile and I'd be happy to merge.

**Comment by Real-Gecko** [comment]
Did that!

**Pull request merged**
