### PR TITLE
Add ability to enter Floating Spirit mode whilst still alive

### PR DESCRIPTION
**Pull request by AdamPlenty**

### CODE REVIEW

**Comment by Loobinex** [comment]
I will not accept this feature, unless it's linked to cheat mode or something. Possession is not available to players without units, or without access to the spell.

**Comment by AdamPlenty** [comment]
You don't need to possess anyone; just click the spell and press the button.

**Comment by Loobinex** [comment]
I understood. What I said is that I will not make this ability available for the player.

**Comment by Loobinex** [comment]
Not good enough. Just having eater egg mode enabled does not mean the player wants to be a cheater.

**Comment by AdamPlenty** [comment]
Then he doesn't have to press the button, does he?

**Pull request closed without merging**
