### PR TITLE
Add Map packs

### PR DESCRIPTION
**Pull request by eddebaby**
See #44

The UI work I did in #186 was headed in the wrong direction. This is the backend code for map packs, and a better path for the UI.

- Map packs are now used to load .lif files that are not part of a campaign. 
- Map packs are defined in the same way as a campaign (with a cfg file). 
- Map pack cfg files should be placed in the /levels/ folder, and they must have LEVELS_LOCATION defined, to provided the list of levels in the pack. 
- All lif files in the directory provided by LEVELS_LOCATION will be loaded in to the map pack as free-play levels.

The Free-Play Levels button on the main menu takes you to a list of map packs. Clicking a map pack takes you to a list of the levels in the map pack.

The UI needs some more work, to make it fully functional. 

UI currently only works with the deeper dungeons (See 9c779a2)

### CODE REVIEW

**Comment by eddebaby** [comment]
Should now allow loading of map packs (and their levels) via menu. UI bugs remain.

Things to check:
- Are the correct configs loaded?
- Are all of the map packs/levels shown? 
- Are the map packs/levels shown in the right order? 
- Are there any missing or extra levels?
- Is the menu flow correct?
- Is the correct menu returned to after leaving a game?
- Does save/load work correctly?
- Are the campaigns negatively effected? Any glitches? Does continue still work the same?

Things to do:
- Fix bugs
- Finalise the UI strings that are needed (and then translate)
- Finalise map pack config file format
- Create map packs
- Move keeporig data to /campgns/keeporig/ (and configs?)
- Move all multiplayer maps to  /campgns/keeporig/ (or handle with new funtionality?)
- Point campaigns/mappacks at the correct configs (creatures, rules etc)

**Comment by eddebaby** [comment]
I will try to add these features next, as they shouldn't take too much time:
- allow lof files (multiplayer maps) in map packs
- move multiplayer levels from map packs to keeporig campaign (this will add all maps to the same selection screen, the same way it works now if you put lof files in the levels folder) [keeporig configs will be used]

I **_could_** look at adding the ability to have multiple multiplayer campaigns (i.e. different map screens, with a different set of levels, configs etc). This would likely involve more changes to the format of the campaign config file. maybe MULTIPLAYER_CAMPAIGN (with a default of NO). I haven't looked at most of the code to do with this yet.

**Comment by Loobinex** [comment]
I agree with you that it's probably best to finish up with this feature first (although I believe when thoroughly tested this pull is ready for merge right?)

As for multiplayer, am I understanding this right:
- In the current master, when starting multiplayer it:
a) Looks only at keeporig.cfg
b) Takes the map screen from keeporig.cfg
c) Takes all levels from the levels folder configured in keeporig.cfg, which is \levels
- With this pull request:
d) It still takes everything from keeporig.cfg
e) But the new levels folder is now \campaigns\keeporig\

If I understand this right, I don't see a need to change the config. Instead, I would expect the behavior to be like this:
1) The player clicks multiplayer
2) The game checks all campaign config files, if in the specified levels folder, there are .lof files present
3) The game lists all campaigns with .lof files for the player to select
4) The player selects one of the campaigns
5) The game displays the campaign landview and levels listed on it
6) The players select a multiplayer level
7) The game loads up the level, with the configs as configured in the campaign config
* The campaign_config does not need to have single player levels included for this to work.

That being said, as long as multiplayer remains basically non-functional, this feature seems very low priority.

**Comment by eddebaby** [comment]
Your descriptions are correct (as far as I understand the code). I think the current master also checks \levels\ for unassigned LIF/LOF files, regardless of the setting in keeporig.cfg.

Your multiplayer solution should be achievable in the code. Step 2 might be the a bit tricky (Currently LOF/LIF files are loaded once the campaign is loaded, as that is when the game "knows" what directory to look in), but I'm sure this can be solved, I just had no need/reason to change this behaviour for single player.

With my idea: I was trying to allow map packs to "add" multiplayer maps to a "multiplayer campaign", The use of different directories, within a single campaign, is what will need bigger changes to the way the code works (and should probably be ignored, as your solution is nice and clean). I guess my hope was to have DK and DD multi levels in different directories, but on the same level select screen (not really necessary!). I will work to your design, if I end up working on the multiplayer campaigns.

And yes - when this is thoroughly tested (and any subsequently needed fixes put in place), this pull request is ready to merge. (CFG files still need to be created, and the levels data reorganised, before any release/distribution.)

**Pull request merged**
