### PR TITLE
Fix useless checks 

### PR DESCRIPTION
**Pull request by StanleySweet**
A few checks (A lot of them actually) trigger warnings because they are comparing unsigned values to either being strictly positive or being negative. This pull request fixes it.

It should be carefully checked though, because there might be some hidden bugs that can be fixed at the same time :)

### CODE REVIEW

**Comment by StanleySweet** [comment]
Anything else :) ?

**Comment by Loobinex** [comment]
The project is a bit on a hiatus again. I've asked spartahawk to review your pull(I have no idea what your stuff does or if it is good or bad, I'm not a programmer) but he's taking a bit of a break from this project, he hopes to continue sometime in the future.

**Comment by Trass3r** [comment]
Just "fixes" a few compiler warnings.
> It should be carefully checked though, because there might be some hidden bugs that can be fixed at the same time :)
This suggests though that code was removed without checking the git history why such odd code is in place.

**Comment by StanleySweet** [comment]
> Just "fixes" a few compiler warnings.
> This suggests though that code was removed without checking the git history why such odd code is in place.

Most of the code I changed wasn't updated when Mefistolis created his special types. In any case if you use an unsigned int and check for > 0 that will return true. The question I was merely asking was whether the existing code with or without the fix might be buggy.

I'll be happy to explain if you have a sepcific concern about a specific file.

**Comment by Loobinex** [comment]
I have no specific concerns. With sparta on break there's no activity on the project at all anyway, and when he gets back he can merge if he wants, this is more his expertise.

**Comment by StanleySweet** [comment]
Sounds good to me.

**Comment by StanleySweet** [comment]
Thanks for the commit!

**Pull request merged**
