### PR TITLE
Fixing the issue with fainted creatures

### PR DESCRIPTION
**Pull request by Schizz**
Pushes away fainted creature when getting hit.

### CODE REVIEW

**Comment by spartahawk** [comment]
Cool. Glad to have another collaborator!

Just a couple style suggestions for consistency:

Could you try to keep semicolons to one per line in the future?

Do you know why guthib seems to always display your added lines with extra indenting? Does your IDE or text editor add spaces or tabs (for spaces is what most of keeperFX code uses -- some files use two spaces)? It always appears fine when I look at it locally but it would be great to have it appear correctly on guthub.

**Comment by spartahawk** [comment]
*four spaces

**Comment by Loobinex** [comment]
I see the code is not identical to before. I'll retest in a few hours and merge afterwards.

**Comment by Schizz** [comment]
It seems to mess the code up by adding tabs which I don't even use, my IDE (visual studio 2015) uses also 4 spaces.

Strange.

**Comment by spartahawk** [comment]
So maybe there's a way to work this so we don't have this issue, but when I pull these changes to make minor edits, it creates a new branch on this repository (Loobinex's). I would have to clone your repository and push to that one. Or you have to make all the changes. Or we create separate pull requests like the last time and close these initial pull requests, every time.

Would you be open to either granting us access to work on your repository, or consider working directly on branches of this repository?

For this one I'm just going to edit from the browser rather than my computer so I don't need to clone your entire repo.

**Comment by spartahawk** [comment]
You know, I think the indentation thing might not be you. This file has different style than most. For example braces begin on the same line rather than a new line. Doesn't really matter. Maybe Mefisto was in Java mode at the time or someone else wrote it.

**Comment by spartahawk** [comment]
Yeah I don't know what the heck is up with that file. I can't get it to work either. Oh well. The code works.

**Comment by Schizz** [comment]
Leave it as it is for now, because I really don't know whether I stay longer or no. If I stay longer with more things to do, you can add me to the repository later then.

I would like to fix the WoP problem as a next. Are you guys aware of all the WoP issues?

**Comment by spartahawk** [comment]
For my own personal reference, and in case others want to be able to make commits to these pull requests from other repositories, this is how that is done via command line. This avoids the problem booth Loobinex and I encountered when pushing changes. I'm going to put this in the wiki too. https://stackoverflow.com/a/9529518/9243004

The "git push git@github.com:git/git.git master"
in this case would be 
"git push git://github.com/Schizz/keeperfx-unofficial.git master"

**Pull request merged**
