### PR TITLE
PushOnHit + Firebomb explosion v2

### PR DESCRIPTION
**Pull request by Loobinex**
Rebalanced firebomb and removed log message.

### CODE REVIEW

**Comment by Loobinex** [comment]
Sorry, now I've got a duplicate. Closing this.
@Schizz, i think you'd better update your pull request. Possible?

**Comment by spartahawk** [comment]
This is a new branch but that's fine.

**Comment by spartahawk** [comment]
Let's reopen this one and just close the other. It's the same thing, and you've already got your changes committed here.

**Comment by spartahawk** [comment]
Git shows some indenting inconsistencies that I'd like to fix (if they are in fact that way), but other than that I see no code issues.

**Comment by Loobinex** [comment]
Sure, fix the indenting.

**Comment by Loobinex** [comment]
@Schizz is my comment on pushonhit in magic.cfg accurate? Happy if I merge the pull request like this?

**Comment by spartahawk** [comment]
Turned out to all just be Github formatting. Okay I pushed that minor edit removing a line fragment. I think we're good to merge if there are no other issues.

**Comment by Loobinex** [comment]
Great. If Schizz is happy as well, I'll merge this pull request.

**Comment by Schizz** [comment]
ye, I am happy

**Comment by Schizz** [comment]
the pushOnHit desc is perfect

**Comment by Loobinex** [comment]
Great, I merged.
Thanks a lot!

**Pull request merged**
