### PR TITLE
Allowed easy laptop frameskip without numpad

### PR DESCRIPTION
**Pull request by spartahawk**
In addition to using the ctrl+ or ctrl- with the numpad keys, it works on the main area of the keyboard as well with the plus and minus keys. For increasing frameskip, it's actually listening for ctrl and the equals key at the same time (since otherwise you would have to push the shift key to change the equals key to plus).

If you like this and merge, maybe don't delete this particular branch, for adding or tweaking hotkeys in the future if anyone has any other suggestions.

### CODE REVIEW

**Comment by Loobinex** [comment]
Tested it on my PC, and when I use Press 'Ctrl =' the frameskip immediately jumps to 512. and the 'Ctrl -" next to it, it jumps straight to 0.
Why?

**Comment by spartahawk** [comment]
I'll have a look
Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Loobinex <notifications@github.com> Date: 2/6/18  1:46 PM  (GMT-10:00) To: Loobinex/keeperfx-unofficial <keeperfx-unofficial@noreply.github.com> Cc: spartahawk <spartahawk.git@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Loobinex/keeperfx-unofficial] Allowed easy laptop frameskip
  without numpad (#9) 
Tested it on my PC, and when I use Press 'Ctrl =' the frameskip immediately jumps to 512. and the 'Ctrl -" next to it, it jumps straight to 0.

Why?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Loobinex/keeperfx-unofficial","title":"Loobinex/keeperfx-unofficial","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Loobinex/keeperfx-unofficial"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Loobinex in #9: Tested it on my PC, and when I use Press 'Ctrl =' the frameskip immediately jumps to 512. and the 'Ctrl -\" next to it, it jumps straight to 0.\r\nWhy?"}],"action":{"name":"View Pull Request","url":"https://github.com/Loobinex/keeperfx-unofficial/pull/9#issuecomment-363605518"}}}

**Comment by Loobinex** [comment]
To be very precise, if I look closely it's not in a single step to max. It just scrolls to max really fast.
Strange, because your code is very straight-forward.

**Comment by spartahawk** [comment]
Looking at how GitHub shows the changes I think there were imbalanced braces that likely caused the issue. I'm away from my computer...if it does the same for the num pad that's it.
-------- Original message --------From: Loobinex <notifications@github.com> Date: 2/6/18  2:31 PM  (GMT-10:00) To: Loobinex/keeperfx-unofficial <keeperfx-unofficial@noreply.github.com> Cc: spartahawk <spartahawk.git@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Loobinex/keeperfx-unofficial] Allowed easy laptop frameskip
  without numpad (#9) 
To be very precise, if I look closely it's not in a single step to max. It just scrolls to max really fast.

Strange, because your code is very straight-forward.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Loobinex/keeperfx-unofficial","title":"Loobinex/keeperfx-unofficial","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Loobinex/keeperfx-unofficial"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Loobinex in #9: To be very precise, if I look closely it's not in a single step to max. It just scrolls to max really fast.\r\nStrange, because your code is very straight-forward."}],"action":{"name":"View Pull Request","url":"https://github.com/Loobinex/keeperfx-unofficial/pull/9#issuecomment-363614175"}}}

**Comment by Loobinex** [comment]
No, the num pad still works fine.

**Comment by spartahawk** [comment]
Should be working correctly now.

**Comment by Loobinex** [comment]
And I'm happy you do usually things. ;-)

Seems to work this time though.

**Pull request merged**
