### PR TITLE
Traps

### PR DESCRIPTION
**Pull request by SimLV**

### CODE REVIEW

**Comment by Loobinex** [comment]
With this build, when I place a boulder trap in an east-west corridor, point my camera east and slap the boulder, it moves towards me. Instead of straight ahead.

Also, and this is probably because of another branch merged in with this, it now always spoils the computer player when you've got 'alex' enabled, which is not right. 'Alex' is not just cheats or development mode, it also gives you some other easter eggs, and people can have 'alex enabled without wanting to cheat at that point. And knowing the AI model is giving something away.
Could you move this feature to be enabled with 'compuchat' instead? That's for when you're debugging the AI, so it makes a lot of sense there.

**Comment by SimLV** [comment]
Ok. I will fix that

**Comment by Loobinex** [comment]
@SimLV When you said you'd fix it, you meant the boulder issue right?

**Comment by Loobinex** [comment]
I reviewed it, and tested it, but it's a massive and I'm sure there's issues left to find. That being said, great job, I'll merge.

**Comment by Loobinex** [comment]
I see this pull goes to the wrong branch. I made a new pull and merged that one instead.

**Pull request closed without merging**
