### PR TITLE
Grenade made useable for creatures

### PR DESCRIPTION
**Pull request by Loobinex**
Redid the changes of the Pull request from Schizz I accidentally closed:

One thing I had to do was assigning target to every shot and not only to navigate missile. So the grenade object stores target id and compares distance and explodes when reaches certain number.
But I must admit I had to use some kind of hack to make it work more realistic. I used some data used for something else to store information about a position of the target at the time when the shot is being created (I used price.number and shot.byte_19 btw) to store those coordination.

Higher level and dexterity the caster is the smaller random radius is made for determining the explosion location.
If the level with combination of dexterity is really high then the grenade explodes not only always at the same place as enemy is but it hits the enemy even while moving. But that's rare. I think there is no actually creature having grenade and also such a high dexterity. I did it just for completeness and for modders who might play with it.

### CODE REVIEW

**Comment by Loobinex** [comment]
@Schizz : When I try to build this PR, I get a build error again:

> YourMaster@Sandy /d/games/keeperfx source/keeperfx
> $ make standard
> mkdir -p obj/std bin
> Building file: src/thing_shots.c
> gcc -I"sdl/include" -c -fmessage-length=0 -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -MMD -MP -MF"obj/std/thing_shots.d" -MT"obj/std/thing_shots.d" -march=i686 -fno-omit-frame-pointer -O3   -DBFDEBUG_LEVEL=0  -o"obj/std/thing_shots.o" "src/thing_shots.c"
> src/thing_shots.c: In function 'update_shot':
> src/thing_shots.c:1337:17: error: 'target_pos' undeclared (first use in this function)
>                  target_pos.x.val = thing->price.number;
>                  ^
> src/thing_shots.c:1337:17: note: each undeclared identifier is reported only once for each function it appears in
> make: *** [obj/std/thing_shots.o] Error 1

**Comment by Schizz** [comment]
I fixed it. https://github.com/Schizz/keeperfx-unofficial/blob/master/src/thing_shots.c

**Comment by Loobinex** [comment]
You did. I updated it, but in case Sparta has some feedback when he reviews your code, I think you can push to this PR with this command:
"git push https://github.com/Loobinex/keeperfx-unofficial.git PR/15"

@spartahawk , right?

**Comment by Loobinex** [comment]
Well, I'm happy. It works fine, think like this it is pretty balanced, even though of course all units with Grenade still get a small boost, and the Ancient Keeper level 3 still works fine.
And of course, very cool that there's an additional spell.

I'd be happy to merge, but of course I'll give sparta a chance to give feedback.

**Comment by spartahawk** [comment]
Sure, I'll review the changes and unless there's a hurry to merge this, it might take a while. I'm still relatively new to this project and tracing potential implications of changes is complicated, or at least requires a good amount of context. I think it's important to understand exactly what was done and any possible impacts. It will also just be a good way for me to better understand the whole project better. This isn't a particularly urgent update I'm assuming...even though it's cool.

**Comment by Schizz** [comment]
Yes. I have put emphasis on the variable accuracy of the grenade in order to make it not overpowered.

I would like to implement the vortex spell as well, but the problem is it doesn't have any visual effect assigned to it. Does anyone happen to know some unused effects in the game?

**Comment by Loobinex** [comment]
I've looked several times before and haven't found any. Is there still any trace of what the vortex spell was supposed to do?

As an alternative, I think a possibility is to abandon the 'disease creature-spell' and replace it with a 'poison arrow'. It's quite easy to duplicate the current arrow sprites, turn them green and add them to the game. The creatures could get a non-contagious disease effect when hit.

**Comment by spartahawk** [comment]
Just for my reference I'm bringing in [these comments](https://github.com/Loobinex/keeperfx-unofficial/pull/19#issuecomment-373490798)...

>>> Schizz, I noticed you used 2d for something when you did it... does that effectively ignore elevation, meaning if the shooting creature is facing the attacked creature (but not necessarily looking directly at it in the vertical plane), it will affect it the same no matter where the attacked creature is in the vertical plane?

>>> Just asking, because from my limited experience with it, this doesn't seem to be what actually happens, but now I'm wondering. If the shooting creature is looking above the target, a meteor will miss, but of course the explosion can still damage nearby creatures. Perhaps you're only using the 2d for the direction to push creatures horizontally away from the 2d location of the explosion? Also for calculating proximity-based damage only from 2d location?

>> I think splash damage is currently calculated in 3d, and the damage dissipates in 3 dimensions, changing it to a 2d view will impact how much damage it does at range.
Also, a meteor exploding on the ceiling above a unit would then do as much damage as a meteor exploding against the unit.

>> This is something that would be quite difficult to test, as somehow the -dbgshots command line option doesn't work anymore. (It is supposed to show the damage done to units from shots).

> Well, the line_of_sight functions only check if there is no obstacle between the shooter and target. And I said that 3d is bugged because it happened to me several times that the projectile exploded in target's face yet no damage was taken because the line_of_sight_3d returned false. When I used 2d version instead, everything went ok and it never happened again.

> Splash damage is calculated according to 3d distance not line of sight, that is as I said only for determining obstacle between two points. And because of that can you imagine a situation where a line between two units is blocked in the vertical plane? I think that's nearly impossible considering DK 1 level architecture. Maybe I am wrong but I really don't see a way to achieve this vertical blocking.

Thanks for the explanation @Schizz

**Comment by spartahawk** [comment]
> You did. I updated it, but in case Sparta has some feedback when he reviews your code, I think you can push to this PR with this command:
"git push https://github.com/Loobinex/keeperfx-unofficial.git PR/15"

> @spartahawk , right?

That's right. After following the command line instructions to checkout this pull request as a new branch from your outside repository, as I explain here https://github.com/Loobinex/keeperfx-unofficial/wiki/Working-with-Git(hub)

**Comment by spartahawk** [comment]
Note to self: when done reviewing, if any new commits are made to this pull request since that merge of master into this branch, merge via command-line, not here, so as to specify no fast-forwarding and preserve branch topology history. https://stackoverflow.com/a/9069127/9243004

`git checkout master`
` git merge --no-ff pr/15` and possibly `--squash` tagged onto that, or done on its own, prior to the merge if multiple options are not allowed in a merge command (determine which is correct) https://stackoverflow.com/a/46516503/9243004

If no new commits are made before ready to merge into master, go ahead and squash & merge from here.

**Comment by spartahawk** [comment]
_Too long; didn't read: I'm happy to merge now, after getting your responses._

Just curious, can either of you show me where splash damage is calculated according to 3d distance? From what I can tell, it's 2d distance, which we did not change.

`distance = get_2d_distance(pos, &tngdst->mappos);`
...
// This sends references of the 3d positions as parameters, but the function only makes use of x and y, not z:
```
MapCoordDelta get_2d_distance(const struct Coord3d *pos1, const struct Coord3d *pos2)
{
    long dist_x,dist_y;
    dist_x = (long)pos1->x.val - (long)pos2->x.val;
    dist_y = (long)pos1->y.val - (long)pos2->y.val;
    return LbDiagonalLength(abs(dist_x), abs(dist_y));
}
```
...
`damage = get_radially_decaying_value(max_damage, max_dist / 4,  3 * max_dist / 4, distance) + 1;` 

Frankly, I don't particularly care if splash damage is based on 2d distance for now. It's super easy to write a 3d distance function though I we can play one later. If it's as I'm seeing, 2d splash damage is how it's been the whole time (this could perhaps be one thing that interferes with word of power working for flying creatures, however...although I'd have to think more about that since you'd suppose 2d should still work as if they were on the ground level with other creatures -- but maybe there's a catch).

Also, it's rare for non-possessed creatures to be flying high up at all, so 2d should work well enough for pretty much all cases anyway unless you're aiming at the ceiling instead of an actual creature, except when creatures are standing at a different elevations (water, guard posts, etc).

And correct me if I'm wrong here... the first if statement in explosion_affecting_thing( ) at line 1282 in thing_effects.c considers the line of sight from the position of the _explosion_ to the thing, not the _shooter_ to the thing. That's probably what you meant though when you wrote that.

Cases **where line of sight will be different** based on where the explosion is vertically can maybe include when a room has a risen feature, like temple, guard post (especially next to water/lava), and perhaps especially the dungeon heart. Also between water and dirt. Water to dirt might only effect short creatures at certain faraway angles, but others (perhaps dungeon heart, water to guard post) could be more in-the-way. For example if an explosion occurs at the base of one side of the raised temple block, and the other is on the other side but in the air, there is line of sight in 3d but not 2d (which I assume is just checking for obstacles in the way from base to base of the x,y position -- but who knows):

line_of_sight_2d() is not rewritten by Mefisto so we can't look at how it is implemented by the game. line_of_sight_3d() is rewritten though (or didn't exist in the first place perhaps) so we can tweak it. _I think I'll go ahead and merge this as-is with 2d line-of-sight checking, and if there is a significant problem with 2d line of sight determined later, we can switch to 3d and try to fix the bug within that 3d line of sight function when applied to this use case._ In fact I'll create an issue to remind me to try it out. Also later we can write another very similar function for 3d coordinate distance calculation for splash damage (there *is* one called `get_3d_box_distance()` used for lightning but we can make another specific one.

**Comment by Loobinex** [comment]
Is [this](https://github.com/dkfans/keeperfx/blob/ea5ee733bcc7837497e1c7b521f2fcc2b6eecfb9/keeperfx/src/creature_senses.c#L140) what you were looking for?

And yeah, I've been killing imps by shooting meteors at the ceiling, but I've got no problem with it. I'm happy to merge.

**Comment by Schizz** [comment]
Yes, excactly.

And I have found the answer why the line_of_sight_3d was not working properly! And it's really a bug!
The reason is that anything which explodes **with the ground** is blocked by line_of_sight_3d function.
Try it yourself: shoot fireball in front of you to the ground and you wont get hit. If you shoot it to the wall standing close you get some friendly fire damage but not if the explosion appears on the ground.

And why did the grenade sometime work and sometime didn't? Because the grenade is jumping thus changing vertical position. So every time the grenade exploded and its vertical position (Z) was with the ground, explosion didn't affect the victim.

**Comment by Loobinex** [comment]
@Schizz I see it the other way around,... I tested the it in the official keeperfx and shooting a meteor against the floor hurts myself. Now I did it with this version from this pull request, and shooting the floor does not hurt me.

**Comment by spartahawk** [comment]
Okay, I'll merge, @Loobinex you can create an alpha release for the current setup, and we can try to use 3d line of sight with the bug fixed in the release after this one. @Schizz for the sake of simplicity, I'm going to create a feature branch on this repository for that 3d line of sight fix. Maybe it's obvious when I'll look at it (I'm going back to bed -- it's late here), but can you point out here in a comment how the code might be fixed?

@Loobinex Aren't you guys saying the same thing as far as how our current setup behaves? Floor explosion doesn't hurt you?

What is considered part of the creature anyway. Are there hit boxes? And do those go all the way to the floor exactly?

**Comment by Loobinex** [comment]
@spartahawk I don't think so. I think Schizz is saying that 3d line of sight has a bug that any explosion on floor level does 0 damage because it thinks it has no line of sight. And that that's the reason he used 2d line of sight.
What I'm saying is that I tested shooting meteors against the floor, and still damage myself, also in the versions where 3d line of sight was still used.. Just with the most recent build that I need to set the blast range high enough to reach me(you can't aim directly down).

**Comment by Schizz** [comment]
Yes, I am saying that 3d line of sight blocks explosion on floor but 2d doesn't.

I think you must be doing something wrong @Loobinex, or some real voodoo is happening here.
This video has been done with a fresh new install of KeeperFX downloaded just today.
www.youtube.com/watch?v=YUzMfGrhsuQ

**Comment by Loobinex** [comment]
I immediately see the difference in your video. You try multiple times, it works sometimes and sometimes it doesn't. I tried it, it worked, I moved on.

So 3d line of sight _sometimes_ blocks explosions on the floor level,....

**Comment by spartahawk** [comment]
FYI I forced an update to the erroneous commit message in the most recent commit to master branch. Please sync before any further branching off this repository that you intend to commit later.

**Comment by Schizz** [comment]
> can you point out here in a comment how the code might be fixed?

adding the '+ 50' seems to fixes the problem.
 ```
    struct Coord3d prevpos;
    struct Coord3d nextpos;
    prevpos.x.val = frpos->x.val;
    prevpos.y.val = frpos->y.val;
    prevpos.z.val = frpos->z.val + 50;
    nextpos.x.val = prevpos.x.val + increase_x;
    nextpos.y.val = prevpos.y.val + increase_y;
    nextpos.z.val = prevpos.z.val + increase_z + 50;
```
You can find it in the line_of_sight_3d function.

**Comment by Loobinex** [comment]
@Schizz I looked at it a bit, and the problem you found isn't random. I took a warlock and backed up into a corner so pushback did not move me, and depending on where I hit the floor I either always damage myself, or never do.

So my working theory is that either the floor is bumpy and sometimes the meteor explodes below ground because of it, or somehow the horizontal orientation/angle matters.

**Comment by Schizz** [comment]
Yes, this is also my conclusion.

**Comment by Schizz** [comment]
You might try it with the fixed I have proposed.

**Comment by Loobinex** [comment]
I did just now, and it doesn't work.

**Comment by Loobinex** [comment]
I did just now, and it doesn't work.

**Comment by Schizz** [comment]
You might try to increase the number as well.

**Comment by Schizz** [comment]
No, none of that. Don't forget this is just checking if there is line between two points, Nothing more, nothing less.

**Comment by Schizz** [comment]
But this lumpy floor is quite annoying.

**Comment by Loobinex** [comment]
yeah, and there's the wall as well. I'm having sparta on chat and we're looking into making the projectile hit 50 pixels earlier instead, so that would work on both walls and floors.

**Comment by Schizz** [comment]
Honestly I haven't experienced any problem with walls. And no matter how hard I try the walls just work fine.

**Comment by Loobinex** [comment]
Here, a packet file and my test level. Run it (with packetload) and you'll see I can shoot that wall spot without any damage taken.
[wallshots.zip](https://github.com/Loobinex/keeperfx-unofficial/files/1821111/wallshots.zip)

**Comment by Schizz** [comment]
This is strange, I was able to reproduce the problem (same place as seen in the packet) only with your build, 
not with mine. I was shooting the wall at the same place under same angle but never.

**Comment by Loobinex** [comment]
All I changed was turn the 2d line of sight back to 3d line of sight.

If you're interested, I made a commit to the 3dDamage branch for Spartahawk to look at. With that change it seems to go well with both floors AND walls.
So it seems to me that floor height is simply returned wrong.

**Pull request merged**
